---
- name: Установить Filebeat 8.19.21
  ansible.builtin.apt:
    name: filebeat=8.19.21
    state: present
  become: true

- name: Настроить Filebeat
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: "0600"
  notify: Перезапустить Filebeat
  become: true

- name: Запустить Filebeat
  ansible.builtin.systemd:
    name: filebeat
    enabled: true
    state: started
  become: true
