---
- name: Обновить кеш apt
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Установить nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  become: true

- name: Развернуть главную страницу
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Запустить nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  become: true
