---
- name: Установить Kibana 8.19.21
  ansible.builtin.apt:
    name: kibana=8.19.21
    state: present
  become: true

- name: Настроить Kibana
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: "0660"
  notify: Перезапустить Kibana
  become: true

- name: Запустить Kibana
  ansible.builtin.systemd:
    name: kibana
    enabled: true
    state: started
    daemon_reload: true
  become: true
